// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBda8nMhX82yTSAHKprgn8Jl1hofwBFiuI',
    appId: '1:901780320219:web:dfedd6dabeff7d830ac1fe',
    messagingSenderId: '901780320219',
    projectId: 'chatgptoncrack-1a9b8',
    authDomain: 'chatgptoncrack-1a9b8.firebaseapp.com',
    storageBucket: 'chatgptoncrack-1a9b8.firebasestorage.app',
    measurementId: 'G-J2JMYFC3XT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW4JTvFT7tRKYQyHXI5notmfyn6URunbM',
    appId: '1:901780320219:android:060e14cf348813b30ac1fe',
    messagingSenderId: '901780320219',
    projectId: 'chatgptoncrack-1a9b8',
    storageBucket: 'chatgptoncrack-1a9b8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT7ZAWCzkBk1D7Gen_ZuoGhkX9d4q4BNg',
    appId: '1:901780320219:ios:86ebf25a560971db0ac1fe',
    messagingSenderId: '901780320219',
    projectId: 'chatgptoncrack-1a9b8',
    storageBucket: 'chatgptoncrack-1a9b8.firebasestorage.app',
    iosBundleId: 'com.example.chatgptoncrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT7ZAWCzkBk1D7Gen_ZuoGhkX9d4q4BNg',
    appId: '1:901780320219:ios:86ebf25a560971db0ac1fe',
    messagingSenderId: '901780320219',
    projectId: 'chatgptoncrack-1a9b8',
    storageBucket: 'chatgptoncrack-1a9b8.firebasestorage.app',
    iosBundleId: 'com.example.chatgptoncrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBda8nMhX82yTSAHKprgn8Jl1hofwBFiuI',
    appId: '1:901780320219:web:137be26d630d1db10ac1fe',
    messagingSenderId: '901780320219',
    projectId: 'chatgptoncrack-1a9b8',
    authDomain: 'chatgptoncrack-1a9b8.firebaseapp.com',
    storageBucket: 'chatgptoncrack-1a9b8.firebasestorage.app',
    measurementId: 'G-SHR29N7MRV',
  );
}
